version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
        PORT: ${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.prod
    command: npm start
    ports:
      - "${PORT}:${PORT}"
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
