version: "3"
services:
  node-app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
#   mongo:
#     image: mongo
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#     volumes:
#       - mongo-db:/data/db
# volumes:
#   mongo-db:
